baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'PLED'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-pled-icon.svg"
  desktop: "images/logo/logo-pled-b.svg"
  desktop_height: "36px"
footer:
  copyright_text: 'Made with ❤️ in Shoreditch, London'

seo:
  meta_og_title: "PLED 2021"
  meta_og_type: "website"
  meta_og_url: ""
  meta_og_image: ""
  meta_og_description: "Pled distributed ledger technology"
  meta_twitter_card: "s"
  meta_twitter_site: ""
  meta_twitter_creator: ""

collections:
  services:
    output: false
  team:
    output: false

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
