# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://pled.io
title: PLED   
email: gaetano.mondelli@gmail.com
#author: Gaetano Mondelli
description: > # "Write an awesome description for your new site here. 
  Automate and scale digital trust
copyright: 'Copyright &copy; 2020 PLED. All Rights Reserved.'
# credits: GaetanoMondelli
#'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# social:
#   - title: twitter
#     url: https://twitter.com/SBootstrap
#   - title: github
#     url: https://github.com/IronSummitMedia/startbootstrap
#   - title: linkedin
#     url: 
